# Generated by Django 4.2.1 on 2023-05-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('star', models.IntegerField()),
                ('comment', models.TextField()),
                ('slug', models.CharField(max_length=500)),
            ],
        ),
    ]
