# Generated by Django 3.2.18 on 2023-05-12 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_roomreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.DeleteModel(
            name='RoomReview',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='specification',
            new_name='property_details',
        ),
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
        migrations.RemoveField(
            model_name='room',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='image_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default='kapan', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='2BHK flat available in kapan aakashedhara', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
