# Generated by Django 3.2.18 on 2023-05-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
