# Generated by Django 3.2.18 on 2023-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_room_google_maps_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='district',
            field=models.CharField(default='Kathmandu', max_length=500),
            preserve_default=False,
        ),
    ]
