# Generated by Django 3.2.18 on 2023-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_room_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Single Room', 'Single Room'), ('Aparment', 'Apartment')], default='Flat', max_length=500),
            preserve_default=False,
        ),
    ]
