# Generated by Django 3.2.18 on 2023-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Single Room', 'Single Room'), ('Apartment', 'Apartment')], max_length=500),
        ),
    ]
