# Generated by Django 3.2.18 on 2023-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230514_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='author_agent_or_owner',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Agent', 'Agent')], default='Owner', max_length=500),
        ),
    ]
